# Fetching the latest node image on alpine linux
FROM node:18.17.1-alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /website

# Installing dependencies
COPY ./package.json /website
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm start


FROM nginx:1.25.2-alpine

WORKDIR /user/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /website/build .


ENTRYPOINT [ "nginx" ,"g","daemon off;"]